name: "Push Docs Check"
on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "tests_app"
          build-command: make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: RefugioDigital/docs/build/html
          force_orphan: true
