name: "Push Docs Check"
on:
  - push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "RefugioDigital/docs/"
          build-command: make html
