name: "Push Docs Check"
on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "RefugioDigital/docs/"
          build-command: make html

      - name: List built files
        run: ls -R RefugioDigital/docs/build/html
        

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: RefugioDigital/docs/build/html