name: "Pull Request Docs Check"
on:
  - push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Crear directorio tmp
        run: mkdir -p /tmp

      - name: Crear archivo log
        run: touch /tmp/sphinx-log

      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
